spring:
  application:
    name: ticket-gateway
  cloud:
    gateway:
      routes:
        - id: ticketing-service
          uri: lb://TICKETING-SERVICE
          predicates:
            - Path=/v1/ticketing/**
        - id: ticket-validation-service
          uri: lb://TICKET-VALIDATION-SERVICE
          predicates:
            - Path=/v1/validation/**

server:
  port: 7777